### ISSUE TITLE
Docker not works

### ISSUE THREAD

**Issue by nosekefik** [jsreport/jsreport-dotnet-example-docker#1]
Returns error

>  Running as root without --no-sandbox is not supported

**Comment by RublenX** [comment]
It happens to me too.

After downloading the project and opening it with "Visual studio 2019", add "users-secrets" from the package console.

`dotnet user-secrets init --project WebApp`

The application starts correctly, but when opening the "Pdf Invoice" menu is when the error "Failed to launch chrome!"

![ErrorDockerJsreport](https://user-images.githubusercontent.com/51078452/81672959-32905800-944b-11ea-97f4-7899101819a3.png)

I have been looking for a solution, everything seems to indicate that it is a dependency problem of "Chrome", but I have not managed to configure "dockerfile" to load them correctly.

I am doing tests because in my company we want to implement this library in AKS with Docker Linux, but if I do not succeed we will look for another alternative.

**Comment by pofider** [comment]
Sorry for the trouble. I've fixed the problem and updated to the latest jsreport and .net core.

> I am doing tests because in my company we want to implement this library in AKS with Docker Linux.

When you have already AKS, it is likely better to run jsreport as an extra POD using our official jsreport docker images and communicate with it externally. This example is about putting everything into the same container - .net core, web app, jsreport binary, jsreport .net sdk. This makes sense only if you want to put everything into one azure web app lets say.

**Comment by RublenX** [comment]
Thank you for your quick response and the correction of the project on GitHub. Now it works perfectly.

I am interested in the information about your official docker images, if you could give me more information about it I would appreciate it.
________________________________
De: Jan Blaha <notifications@github.com>
Enviado: martes, 12 de mayo de 2020 16:06
Para: jsreport/jsreport-dotnet-example-docker <jsreport-dotnet-example-docker@noreply.github.com>
Cc: Juan Rubén <juanru@outlook.com>; Comment <comment@noreply.github.com>
Asunto: Re: [jsreport/jsreport-dotnet-example-docker] Docker not works (#1)


Sorry for the trouble. I've fixed the problem and updated to the latest jsreport and .net core.

I am doing tests because in my company we want to implement this library in AKS with Docker Linux.

When you have already AKS, it is likely better to run jsreport as an extra POD using our official jsreport docker images and communicate with it externally. This example is about putting everything into the same container - .net core, web app, jsreport binary, jsreport .net sdk. This makes sense only if you want to put everything into one azure web app lets say.

**Comment by pofider** [comment]
I prepared another example that shows how to run jsreport in an extra container. It can be found [here](https://github.com/jsreport/jsreport-dotnet-example-docker-compose). The example is using docker-compose to orchestrate containers, however, with AKS it is just about the same idea.

**Comment by RublenX** [comment]
Thanks for the information, I will be attentive to the example you upload.

I need to be able to set the title metadata in the PDF file. I read in the forum is only possible using wkhtmltopdf. I have tried it by C # code, but it gives me an error:

Recipe 'wkhtmltopdf' not found

I have modified the file "dockerfile" and I have included:

RUN apt-get install -y wkhtmltopdf

But it still doesn't work. Do I open a thread in the forum or can you answer me here?
________________________________
De: Jan Blaha <notifications@github.com>
Enviado: martes, 12 de mayo de 2020 21:10
Para: jsreport/jsreport-dotnet-example-docker <jsreport-dotnet-example-docker@noreply.github.com>
Cc: Juan Rubén <juanru@outlook.com>; Comment <comment@noreply.github.com>
Asunto: Re: [jsreport/jsreport-dotnet-example-docker] Docker not works (#1)


I prepared another example that shows how to run jsreport in an extra container.
It can be found here<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjsreport%2Fjsreport-dotnet-example-docker-compose&data=02%7C01%7C%7C5d9a38dea7cf4462a11c08d7f6a82a2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637249074424080176&sdata=PFC0euhTrqQEmBBgwj87qyn0Cjzy7pN12mOMKeQ9%2Fc0%3D&reserved=0>
The example is using docker-compose to orchestrate containers, however, with AKS it is just about the same idea.

**Comment by pofider** [comment]
I recommend forgetting about c# and docker for a moment and start the easy path and then complicate it. Start with [installing jsreport](https://jsreport.net/on-prem) to your dev PC and play with it a bit. Then check the list of [custom extensions](https://jsreport.net/learn/extensions) and install [pdf meta](https://jsreport.net/learn/pdf-meta) extension. You should quickly see it does what you need. In the meantime, I will try to extend some c# examples to show more what can jsreport do.

Please ask on our forum in the future https://forum.jsreport.net/. This issue is getting off-topic.
